### PR TITLE
Add missing version strings for dependent crates

### PR DESCRIPTION
**Pull request by nick-mobilecoin**
In order to publish crates *all* dependencies should specify the
versions.  Previously some local crates were not specifying the version,
now they all are.

### CODE REVIEW

**Comment by nick-mobilecoin** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #63** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/63" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/63?utm_source=stack-comment).

**Review by awygle — CHANGES_REQUESTED** [review]
The `capable` library and the `test_enclave` both have references to local crates that don't have versions associated. Also, the `urts` library has a reference to the `test_enclave` with no version.

**Comment by nick-mobilecoin** [comment]
The other missing ones should be added now

**Review by awygle — APPROVED** [review]

**Comment by jcape** [comment]
I'm holding off on a review b/c I think all this should be fixed by #61

**Review by jcape — APPROVED** [review]

**Pull request merged**
