### PR TITLE
Add `cargo release` configuration

### PR DESCRIPTION
**Pull request by nick-mobilecoin**

### CODE REVIEW

**Comment by nick-mobilecoin** [comment]
Current dependencies on/for this PR:
* main
  * **PR #147** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/147" target="_blank">Graphite</a> 
    * **PR #148** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/148" target="_blank">Graphite</a> 
      * **PR #149** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/149" target="_blank">Graphite</a> 
        * **PR #150** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/150" target="_blank">Graphite</a> 
          * **PR #151** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/151" target="_blank">Graphite</a> 
            * **PR #153** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/153" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/153?utm_source=stack-comment).

**Review by NotGyro — APPROVED** [review]
Looks good to me.

**Review by awygle — APPROVED** [review]
These look good to me

**Review by jcape — APPROVED** [review]

**Comment by nick-mobilecoin** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/153?utm_source=stack-comment).


Job Reference: MTlCz31pHORkTM9rocyb

**Pull request merged**
