### PR TITLE
Add `Condvar` to `mc-sgx-tstdc`

### PR DESCRIPTION
**Pull request by nick-mobilecoin**

### CODE REVIEW

**Comment by nick-mobilecoin** [comment]
Current dependencies on/for this PR:
* main
  * **PR #255** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/255" target="_blank">Graphite</a> 
    * **PR #256** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/256" target="_blank">Graphite</a> 
      * **PR #259** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/259" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/259?utm_source=stack-comment).

**Review by samdealy — APPROVED** [review]

**Review by NotGyro — APPROVED** [review]
This looks good to me.

**Comment by nick-mobilecoin** [comment]
⏳ This pull request is set to merge as part of a Graphite merge job
Stack job ID: oVCQ2kHpI2qOxWNUHTpX.
See details on [graphite.dev](https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/259)

**Comment by nick-mobilecoin** [comment]
@samdealy bumped you for re-review since I needed to restack

**Review by samdealy — APPROVED** [review]

**Pull request merged**
