### PR TITLE
Remove test check from `no_std` usage

### PR DESCRIPTION
**Pull request by nick-mobilecoin**

### CODE REVIEW

**Comment by nick-mobilecoin** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #23** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/23" target="_blank">Graphite</a> 
    * **PR #2** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/2" target="_blank">Graphite</a> 
      * **PR #24** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/24" target="_blank">Graphite</a> 
        * **PR #6** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/6" target="_blank">Graphite</a> 
          * **PR #26** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/26" target="_blank">Graphite</a> 
            * **PR #8** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/8" target="_blank">Graphite</a> 
              * **PR #9** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/9" target="_blank">Graphite</a> 
                * **PR #30** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/30" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/30?utm_source=stack-comment).

**Review by awygle — APPROVED** [review]
LGTM! Bit surprised you don't have to import TryInto anymore, but it still runs. Guess that's in the core prelude?

**Review by NotGyro — APPROVED** [review]
This works on my end, tests passing. It looks like it's all set!

**Comment by nick-mobilecoin** [comment]
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx/30?utm_source=stack-comment).


Job Reference: tCEFOsXmIVR1PvpWOGXr

**Pull request merged**
